### PR TITLE
feat: add helm deploy

### PR DESCRIPTION
**Pull request by xgui3783**
solves #4

### CODE REVIEW

**Comment by xgui3783** [comment]
also supercedes https://github.com/HumanBrainProject/hbp-spatial-backend/pull/3

**Comment by xgui3783** [comment]
The PR should be largely ready. Can you take a look and provide some feedback?

The hanging tests is likely misconfigured branch protection rules. 

ping @ylep and @JoelChavas

**Review by ylep — APPROVED** [review]
I am completely ignorant of k8s and helm, so you have my full trust here, feel free to proceed with the merge!

@xgui3783 we now have container images including `AimsApplyTransform` that are based on Ubuntu 22.04, I should probably prepare a Docker version so that you can finally upgrade from obsolete dependencies (Ubuntu 18.04, Python 3.6)... ? Feel free to open an issue regarding that duty, and assign it to me.

**Comment by xgui3783** [comment]
Apologies, I only just now have time to report on this PR. 

I can report that the spatial backend is running well on the new k8s cluster

```sh
$ kubectl get all
NAME                                            READY     STATUS    RESTARTS       AGE
pod/busy-box-7fdc68fbfc-gbx7f                   1/1       Running   1 (105d ago)   106d
pod/prod-hbp-spatial-backend-7f644f74ff-g2gpc   1/1       Running   1 (105d ago)   106d
pod/prod-hbp-spatial-backend-7f644f74ff-pxqd9   1/1       Running   6 (65d ago)    113d
pod/prod-hbp-spatial-backend-7f644f74ff-xgms9   1/1       Running   3 (65d ago)    106d

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/prod-hbp-spatial-backend   ClusterIP   10.43.180.189   <none>        8080/TCP   113d

NAME                                       READY     UP-TO-DATE   AVAILABLE   AGE
deployment.apps/busy-box                   1/1       1            1           113d
deployment.apps/prod-hbp-spatial-backend   3/3       3            3           113d

NAME                                                  DESIRED   CURRENT   READY     AGE
replicaset.apps/busy-box-7fdc68fbfc                   1         1         1         113d
replicaset.apps/prod-hbp-spatial-backend-7f644f74ff   3         3         3         113d
replicaset.apps/prod-hbp-spatial-backend-b865588d6    0         0         0         113d
replicaset.apps/prod-hbp-spatial-backend-bb689d979    0         0         0         113d
```

the URL of the deployed service is at https://siibra-spatial-backend.apps.tc.humanbrainproject.eu/ , and we have a monitoring cron job running at https://github.com/FZJ-INM1-BDA/iav-dep-test/actions/workflows/siibra.dep.yml to monitor the health of the endpoint (e.g. https://github.com/FZJ-INM1-BDA/iav-dep-test/actions/runs/8295730452/job/22703360465 which monitors the new endpoint)

I lack the sufficient right to merge in this repo. If you have a chance can you

a/ update the merge checklist and
b/ merge the PR?

ping @ylep

**Comment by ylep** [comment]
I couldn't find a way of updating the merge checklist... hope the force-merge is fine.

**Pull request merged**
